### ISSUE TITLE
Fork Clojure language implementation to ua-parser project?

### ISSUE THREAD

**Issue by russellwhitaker** [ua-parser/ua-parser.github.io#3]
I've completed the Clojure language implementation (v1.0.0) of the ua-parser/uap-core specification:

https://github.com/russellwhitaker/uap-clj

Would there be interest in forking this to the ua-parser project?

Relatedly, I've also just today released an Apache Hadoop Hive GenericUDF wrapper around the core Clojure uap-clj library, uap-clj-hiveudf: 

https://github.com/russellwhitaker/uap-clj-hiveudf

Russell

**Comment by russellwhitaker** [comment]
@tobie any interest? Latest version is v1.0.3 and available on Clojars: https://clojars.org/uap-clj

I'm pretty actively maintaining this and derivatives such an Apache Hadooop Hive UDF wrapper and an Amazon AWS Lambda function wrapper I released today.

**Comment by tobie** [comment]
Should be enabled now. LMK if there's anything you still need (maybe to do the transfer?)

**Comment by russellwhitaker** [comment]
@tobie thanks, I'm investigating both forking and non-forking (i.e. git mirror) options on that new repo from my upstream uap-clj; thanks for adding me to the organization, much appreciated.
